# -*- coding: utf-8 -*-
"""Data Analysis Hotel Booking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPsJnKS-4ugdGxd8wbnFxnpvXK-DACR9

Importing Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""Loading the dataset"""

df = pd.read_csv('dataset.csv')

"""EDA Exploratory Data Analysis and Data Cleaning"""

df.head()

df.tail()

df.shape

df.columns

df.info()

# Convert 'reservation_status_date' to datetime
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'], format='%d/%m/%Y')

df.describe(include = 'object')

for col in df.describe(include = 'object').columns:
    print(col)
    print(df[col].unique())
    print('-'*50)

df.isnull().sum()

df.dropna().isnull().sum()

df.describe()

df = df[df['adr']<5000]

df.describe()

"""Data Analysis and Visualizations (Analysis And Findings)"""

cancelled_perc = df['is_canceled'].value_counts(normalize = True)
print(cancelled_perc)

plt.figure(figsize = (5,4))
plt.title('Reservation Status Count')
plt.bar(['Not Cancelled',' Cancelled'],df['is_canceled'].value_counts(),edgecolor = 'k',width = 0.7)
plt.xlabel('Reservation Status')
plt.ylabel('Percentage')
plt.show()

"""***The accompanying bar graph shows the percentage of reservations that are canceled and those that are not. It is obvious that there are still a significant number of reservations that have not been canceled.There are still 37% of clients who canceled their reservation,which has a significant impact on the hotel's earning.***"""

plt.figure(figsize = (8,4))
ax1=sns.countplot(x='hotel',hue='is_canceled',data=df,palette='Blues')
legend_labels,_ = ax1.get_legend_handles_labels()
plt.title('Reservation Status in different Hotels')
plt.xlabel('Hotel')
plt.ylabel('No of Reservations')
plt.legend(['Not Canceled', 'Canceled'])
plt.show()

"""***In comparison to resort hotels,city hotels have more bookings.It's possible that resort hotel's are more expensive than thse in cities.***"""

resort_hotel = df[df['hotel']=='Resort Hotel']
resort_hotel['is_canceled'].value_counts(normalize = True)

city_hotel = df[df['hotel']=='City Hotel']
city_hotel['is_canceled'].value_counts(normalize = True)

resort_hotel = resort_hotel.groupby('reservation_status_date')['adr'].mean()
city_hotel = city_hotel.groupby('reservation_status_date')['adr'].mean()

plt.figure(figsize = (10,4))
plt.title('Average Daily Rate in City and Resort Hotels')
plt.plot(resort_hotel.index, resort_hotel,label = 'Resort Hotel')
plt.plot(city_hotel.index, city_hotel,label = 'City Hotel')
plt.show()

"""***The line graph above shows that, on certain days, the average daily rate for a city hotel is less than that of a resort hotel, and on other days,it is even less. It goes without saying that weekends and hoildays may see a rise in resort hotel rates.***"""

df['month'] = df['reservation_status_date'].dt.month
plt.figure(figsize=(10,4))
ax1 = sns.countplot(x='month',hue='is_canceled',data=df,palette='bright')
legend_labels,_ = ax1.get_legend_handles_labels()
ax1.legend(bbox_to_anchor=(1,1))
plt.title('Reservation Status in each month')
plt.xlabel('Month')
plt.ylabel('No of Reservations')
plt.legend(['Not Canceled', 'Canceled'])
plt.show()

"""***We have developed the grouped bar graph to analyze the months with the highest and lowest reservation levels according to reservations and the number of canceled reservations are largest in the month of august whereas January is the moth with the most canceled reservations.***"""

plt.figure(figsize = (10,4))
plt.title('ADR per month')
sns.barplot(x='month', y='adr', data=df[df['is_canceled'] == 1].groupby('month')[['adr']].sum().reset_index())
plt.xlabel('Month')
plt.ylabel('ADR')
plt.show()

"""***This bar graph demonstrates that cancellations are most common when prices are greatest and are least common when they are lowest.Therefore,thecost of the accommodation is solely responsible for the cancellation.***


"""

cancelled_data = df[df['is_canceled'] == 1]
top_10_country = cancelled_data['country'].value_counts()[:10]
plt.figure(figsize = (10,5))
plt.title('Top 10 Countries with Reservations Canceled')
plt.pie(top_10_country, labels = top_10_country.index, autopct = '%.2f')
plt.show()

"""***Now, let's see which country has the highest reservation canceled. The top country is Portugal with the highest number of cancellations.***

***Let's check the area from where guest are visiting the hotels and making reservations.Is it coming from Direct, Group,Online,Offline Travel Agents? Around 46% of the clients come from online travel agencies,whereas 27% come from groups. Only 4% of clients book hotels directly by visiting them and making reservations.***
"""

df['market_segment'].value_counts()

df['market_segment'].value_counts(normalize=True)

cancelled_data['market_segment'].value_counts(normalize=True)

cancelled_df_adr = cancelled_data.groupby('reservation_status_date')['adr'].mean()
cancelled_df_adr = cancelled_df_adr.reset_index()
cancelled_df_adr.sort_values('reservation_status_date', inplace = True)

not_cancelled_df_adr = df[df['is_canceled'] == 0]
not_cancelled_df_adr = not_cancelled_df_adr.groupby('reservation_status_date')['adr'].mean()
not_cancelled_df_adr = not_cancelled_df_adr.reset_index()
not_cancelled_df_adr.sort_values('reservation_status_date', inplace = True)

plt.figure(figsize = (10,4))
plt.title('Average Daily Rate in Cancelled and Not Cancelled Reservations')
plt.plot(not_cancelled_df_adr['reservation_status_date'], not_cancelled_df_adr['adr'],label = 'Not Canceled')
plt.plot(cancelled_df_adr['reservation_status_date'], cancelled_df_adr['adr'],label = 'Canceled')
plt.legend()
plt.show()

filtered_df = df[(df['reservation_status_date'] >= '2016-01-01') & (df['reservation_status_date'] <= '2017-09-30')]

plt.figure(figsize=(10, 4))
plt.title('Average Daily Rate for Cancelled and Not Cancelled Reservations')

# Filter data for the specified date range
cancelled_df_filtered = cancelled_df_adr[(cancelled_df_adr['reservation_status_date'] >= '2016-01-01') & (cancelled_df_adr['reservation_status_date'] <= '2017-09-30')]
not_cancelled_df_filtered = not_cancelled_df_adr[(not_cancelled_df_adr['reservation_status_date'] >= '2016-01-01') & (not_cancelled_df_adr['reservation_status_date'] <= '2017-09-30')]

plt.plot(not_cancelled_df_filtered['reservation_status_date'], not_cancelled_df_filtered['adr'], label='Not Cancelled')
plt.plot(cancelled_df_filtered['reservation_status_date'], cancelled_df_filtered['adr'], label='Cancelled')

plt.xlabel('Date')
plt.ylabel('Average Daily Rate (ADR)')
plt.legend()
plt.show()

"""***As seen in thhe graph, reservations are cancelled when the average daily rate is higher than when it is not canceled.It clearly proves all the above analysis,that the higher price leads to higher cancellation.***

***Suggestions***

***1.Cancellation rates rise as the price does. In order to prvent cancellations of reservations,hotel could work on their pricing strategies and try to lower the rates for specific hotels based on locations.They can also provide some discounts to the consumers.***

***2.As the ratio of the cancellation and not cancellation of the resort hotel in higher the resort hotel than the city hotels. So the hotels should provide a reasonable discount on the room prices on weekends or on hoildays.***

***3.In the month of January, hotels can start campaigns or making with a reasonable amount to increase their revenue as the cancellation is the highest in this month.***

***4.they can also increase the quality of their hotels and their services mainly in Portugal to reduce the cancellation rate.***
"""